### ISSUE TITLE
Disabled tests in Chromium

### ISSUE THREAD

**Issue by Hexcles** [bocoup/wpt-disabled-tests-report#6]
Hi @zcorpan , the dashboard looks awesome!

Chromium has another list for disabled/wontfix tests:
https://cs.chromium.org/chromium/src/third_party/WebKit/LayoutTests/NeverFixTests

`TestExpectations` only contains flaky / temporarily disabled tests, whereas `NeverFixTests` contains, well, tests that will "never" be fixed, many of which are simply manual tests but there are some disabled for other reasons. Unfortunately, there is no way to tell the two kinds apart reliably, but one heuristic is that the lines without bug links are almost all manual tests, so you may look at those with bugs associated.

**Comment by zcorpan** [comment]
Maybe I can include the manual tests as well -- I think those should be renamed to -manual.html and not listed in that file.

**Comment by zcorpan** [comment]
Thanks!
