### ISSUE TITLE
Ability to filter tests

### ISSUE THREAD

**Issue by zcorpan** [bocoup/wpt-disabled-tests-report#7]
@foolip would it be useful to be able to filter tests, so a team responsible for a set of tests can check their tests?

**Comment by foolip** [comment]
The report still isn't super long, so searching in the page is probably sufficient for now, until someone spontaneously requests filtering :)

**Comment by zcorpan** [comment]
It would be quick to implement though, made a prototype in devtools in a few minutes ☺

**Comment by zcorpan** [comment]
I went ahead an implemented this. :)
